#!/bin/bash

sleep 1
echo Step 1
sleep 1
echo Step 2
sleep 1
echo Step 3
sleep 1
echo Step 4
sleep 1
echo Step 5
sleep 1
echo Step 6
sleep 1
echo Step 7
sleep 1
echo Step 8
sleep 1
echo Step 9
sleep 1
echo Step 10
sleep 1

grep -q
sleep 2
